name: Test

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm run test
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        run: echo "$AWS_STARPORT_BAR_AK"
      - name: Dump runner context
        run: echo "$AWS_STARPORT_BAR_SAK"
      - name: Dump runner context
        run: echo "$REPOSITORY_ID"
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_STARPORT_BAR_AK }}
          aws_secret_access_key: ${{ secrets.AWS_STARPORT_BAR_SAK }}
          aws_bucket: startport-bar
          source_dir: 'src/docs'
          destination_dir: ${{ secrets.REPOSITORY_ID }}
