name: Test

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm run test
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIAS3SK47SIEK3IAPD6
          aws_secret_access_key: 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
          aws_bucket: testdocsbucketlaunchpad
          source_dir: 'src/docs'
          destination_dir: '705002784'
